// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using doctrine_api.Services.SQLServer;

#nullable disable

namespace doctrineapi.Migrations
{
    [DbContext(typeof(DoctrinaStore))]
    [Migration("20230125115807_doctrina-api.v1")]
    partial class doctrinaapiv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("doctrine_api.DataModels.Account", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("IMAGE")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LAST_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIDDEL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD_HASH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PHONE_NUMBER")
                        .HasColumnType("int");

                    b.Property<byte[]>("SALT")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.ToTable("ACCOUNT");
                });
#pragma warning restore 612, 618
        }
    }
}
